export enum CacheKeys {
  USERS = 'USERS',
  USER = 'USER',
  PATIENTS = 'PATIENTS',
  PATIENT = 'PATIENT',
  APPOINTMENTS = 'APPOINTMENTS',
  APPOINTMENT = 'APPOINTMENT',
  APPOINTMENTS_BY_PATIENT = 'APPOINTMENTS_BY_PATIENT',
  DOCTORS = 'DOCTORS',
  DOCTOR = 'DOCTOR',
}
